/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import java.awt.Font;

/**
 *
 * @author USUARIO
 */
public class Interfaz4 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz4
     */
    public Interfaz4() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana4 = new javax.swing.JPanel();
        acompañamiento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acomp1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        siguiente3 = new javax.swing.JButton();
        acomp2 = new javax.swing.JLabel();
        acomp3 = new javax.swing.JLabel();
        acomp4 = new javax.swing.JLabel();
        acomp5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ventana4.setBackground(new java.awt.Color(49, 174, 96));

        acompañamiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acompañamiento.setText("ACOMPAÑAMIENTO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/acompañamiento-removebg-preview (1).png"))); // NOI18N

        acomp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acomp1.setText("Chips de verduras");
        acomp1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(46, 213, 115));

        siguiente3.setBackground(new java.awt.Color(204, 102, 0));
        siguiente3.setText("Siguiente");
        siguiente3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(siguiente3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siguiente3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        acomp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acomp2.setText("Salsa romesco");
        acomp2.setOpaque(true);

        acomp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acomp3.setText("Huevo poché");
        acomp3.setOpaque(true);

        acomp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acomp4.setText("Cebolla caramelizada");
        acomp4.setOpaque(true);

        acomp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acomp5.setText("Verduras salteadas");
        acomp5.setOpaque(true);

        javax.swing.GroupLayout Ventana4Layout = new javax.swing.GroupLayout(Ventana4);
        Ventana4.setLayout(Ventana4Layout);
        Ventana4Layout.setHorizontalGroup(
            Ventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Ventana4Layout.createSequentialGroup()
                .addGroup(Ventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ventana4Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(Ventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(acompañamiento)))
                    .addGroup(Ventana4Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(Ventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acomp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acomp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acomp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acomp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acomp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        Ventana4Layout.setVerticalGroup(
            Ventana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acompañamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(acomp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acomp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acomp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acomp4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acomp5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente3ActionPerformed
        // TODO add your handling code here:
        Interfaz5 d = new Interfaz5();
        d.setVisible(true);
        this.setVisible(false);
        
        //Fuentes
        acompañamiento.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        acomp1.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        acomp2.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        acomp3.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        acomp4.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        acomp5.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        siguiente3.setFont(new Font(Font.SANS_SERIF,Font.ITALIC,18));

                                
    }//GEN-LAST:event_siguiente3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ventana4;
    private javax.swing.JLabel acomp1;
    private javax.swing.JLabel acomp2;
    private javax.swing.JLabel acomp3;
    private javax.swing.JLabel acomp4;
    private javax.swing.JLabel acomp5;
    private javax.swing.JLabel acompañamiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton siguiente3;
    // End of variables declaration//GEN-END:variables
}
