/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import java.awt.Font;

/**
 *
 * @author USUARIO
 */
public class Interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz2
     */
    public Interfaz2() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vnetana2 = new javax.swing.JPanel();
        entrada = new javax.swing.JLabel();
        entrada1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        siguiente1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        entrada2 = new javax.swing.JLabel();
        entrada3 = new javax.swing.JLabel();
        entrada4 = new javax.swing.JLabel();
        entrada5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vnetana2.setBackground(new java.awt.Color(255, 255, 153));

        entrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada.setText("MENÚ - ENTRADA");

        entrada1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada1.setText("Coliflor al horno, asada con salsa barbacue");
        entrada1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(205, 97, 51));

        siguiente1.setBackground(new java.awt.Color(204, 102, 0));
        siguiente1.setText("Siguiente");
        siguiente1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(siguiente1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siguiente1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/chefsita-removebg-preview (1).png"))); // NOI18N

        entrada2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada2.setText("Choclos a la parrilla con soya y ají");
        entrada2.setOpaque(true);

        entrada3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada3.setText("Crema de espinacas casera");
        entrada3.setOpaque(true);

        entrada4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada4.setText("Champiñones rellenos");
        entrada4.setOpaque(true);

        entrada5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrada5.setText("Sopa de pollo");
        entrada5.setOpaque(true);

        javax.swing.GroupLayout Vnetana2Layout = new javax.swing.GroupLayout(Vnetana2);
        Vnetana2.setLayout(Vnetana2Layout);
        Vnetana2Layout.setHorizontalGroup(
            Vnetana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Vnetana2Layout.createSequentialGroup()
                .addGroup(Vnetana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vnetana2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(Vnetana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entrada)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Vnetana2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(Vnetana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entrada1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(entrada2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entrada3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entrada4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entrada5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        Vnetana2Layout.setVerticalGroup(
            Vnetana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vnetana2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(entrada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrada5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vnetana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vnetana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente1ActionPerformed
        // TODO add your handling code here:
        Interfaz3 b = new Interfaz3();
        b.setVisible(true);
        this.setVisible(false);
        
        //Fuentes
        entrada.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        entrada1.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        entrada2.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        entrada3.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        entrada4.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        entrada5.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        siguiente1.setFont(new Font(Font.SANS_SERIF,Font.ITALIC,18));
    }//GEN-LAST:event_siguiente1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Vnetana2;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel entrada1;
    private javax.swing.JLabel entrada2;
    private javax.swing.JLabel entrada3;
    private javax.swing.JLabel entrada4;
    private javax.swing.JLabel entrada5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton siguiente1;
    // End of variables declaration//GEN-END:variables
}
