/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import java.awt.Font;

/**
 *
 * @author USUARIO
 */
public class Interfaz3 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz3
     */
    public Interfaz3() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana3 = new javax.swing.JPanel();
        platofuerte = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plato1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        siguiente2 = new javax.swing.JButton();
        plato2 = new javax.swing.JLabel();
        plato3 = new javax.swing.JLabel();
        plato4 = new javax.swing.JLabel();
        plato5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ventana3.setBackground(new java.awt.Color(204, 174, 98));

        platofuerte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        platofuerte.setText("PLATO FUERTE");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/platofuerte-removebg-preview (1).png"))); // NOI18N

        plato1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plato1.setText("Pavo en salsa de frutos secos");
        plato1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(247, 183, 49));

        siguiente2.setBackground(new java.awt.Color(204, 102, 0));
        siguiente2.setText("Siguiente");
        siguiente2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(siguiente2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siguiente2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        plato2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plato2.setText("Lomo de cerdo criollo");
        plato2.setOpaque(true);

        plato3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plato3.setText("Alitas en salsa artesanal de panela");
        plato3.setOpaque(true);

        plato4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plato4.setText("Brochetas de res y pollo");
        plato4.setOpaque(true);

        plato5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plato5.setText("Pasta en salsa carbonara");
        plato5.setOpaque(true);

        javax.swing.GroupLayout Ventana3Layout = new javax.swing.GroupLayout(Ventana3);
        Ventana3.setLayout(Ventana3Layout);
        Ventana3Layout.setHorizontalGroup(
            Ventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Ventana3Layout.createSequentialGroup()
                .addGroup(Ventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plato5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Ventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Ventana3Layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Ventana3Layout.createSequentialGroup()
                            .addGap(169, 169, 169)
                            .addComponent(platofuerte))
                        .addGroup(Ventana3Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addGroup(Ventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(plato3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plato4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        Ventana3Layout.setVerticalGroup(
            Ventana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(platofuerte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plato2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plato1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plato3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plato4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plato5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente2ActionPerformed
        // TODO add your handling code here:
        Interfaz4 c = new Interfaz4();
        c.setVisible(true);
        this.setVisible(false);
        
        //Fuentes
        platofuerte.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        plato1.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        plato2.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        plato3.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        plato4.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        plato5.setFont(new Font(Font.SANS_SERIF,Font.BOLD,22));
        siguiente2.setFont(new Font(Font.SANS_SERIF,Font.ITALIC,18));
    }//GEN-LAST:event_siguiente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ventana3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel plato1;
    private javax.swing.JLabel plato2;
    private javax.swing.JLabel plato3;
    private javax.swing.JLabel plato4;
    private javax.swing.JLabel plato5;
    private javax.swing.JLabel platofuerte;
    private javax.swing.JButton siguiente2;
    // End of variables declaration//GEN-END:variables
}
